### ISSUE TITLE
Available Depth modes

### ISSUE THREAD

**Issue by Stephan1994** [Vzense/Vzense_SDK_Windows#1]
Hi,

could you please explain the possible depth modes. I could only find estimated ranges for the modes `PsNearRange` (150 - 1500 mm), `PsMidRange` (500 - 2800 mm) and `PsFarRange` (800 - 4400 mm). What is the difference to the X and XX modes? And which of the modes is actually available on the DCAM710?

Extracted from [Vzense_enums_710.h](https://github.com/Vzense/Vzense_SDK_Windows/blob/master/Include/DCAM710/Vzense_enums_710.h):
```c++
typedef enum {
	PsUnknown = -1,
	PsNearRange = 0,               
	PsMidRange = 1,                
	PsFarRange = 2,                
	PsXNearRange = 3,              
	PsXMidRange = 4,               
	PsXFarRange = 5,               
	PsXXNearRange = 6,             
	PsXXMidRange = 7,              
	PsXXFarRange = 8               
}PsDepthRange;
```

**Comment by Teemovzense** [comment]
Different modes represent different measured distances. 150-1500 mm is the usual measurement distance for PsNearRange mode, which can be adjusted during factory production. In fact, the description (150-1500 mm) has been removed from the latest version.

The available modes of the DCAM710 can be viewed using Utool.
[https://github.com/Vzense/UTool](url)

As shown in the figure below, the available modes are Range0, Range2, and Range5.
![available modes](https://user-images.githubusercontent.com/65522599/139794972-cfefa976-c24e-4915-9b66-6dce507118aa.png)
