### ISSUE TITLE
Customization of depth range for short/close range

### ISSUE THREAD

**Issue by melsanharawi** [Vzense/Vzense_SDK_Windows#2]
Hi,
Currently,  there are 3 different range modes calibrated for the Tof Camera (0.35-1.4m, 0.5-2.5m, 0.8-4m)
Is it possible to add a new range : 0.15m and 0.6m ?
In that way, the camera could be used to make 3D scanning of small and medium objects.

Thanks.

**Comment by peter-vzense** [comment]
Thanks for your reminding.
The new DCAM560C model have this range now.
