### ISSUE TITLE
Integrate DCAM710 with C#

### ISSUE THREAD

**Issue by phuongdcd-spartronics** [Vzense/Vzense_SDK_Windows#3]
I have tried to open DCAM710 with camera application on Windows 10 but it's not work well.
I want to integrate it in C# Project but it couldn't work.
I also run VZenseUtool to upgrade the lasted firmware version but the result remains unchanged.
Please tell me know how to control this camera in C#?

**Comment by peter-vzense** [comment]
Currently there are only C and python version SDK on windows. if you want C#, you could write one wrapper to call C library.
