### ISSUE TITLE
DCAM550P光源无法关闭

### ISSUE THREAD

**Issue by wyfrily** [Vzense/Vzense_SDK_Windows#4]
你好，

经过我们验证，DCAM550P一上电就会点亮光源，通过UTool关闭设备后，光源仍不关闭。
在B41以及最新的B42固件版本上均是如此。

请问这是BUG还是有其他原因？

**Comment by peter-vzense** [comment]
设计如此，可以调用接口进行关闭。参考Ps2_SetSlaveModeEnabled的接口使用
