### ISSUE TITLE
image writing

### ISSUE THREAD

**Issue by Rans1234** [Vzense/Vzense_SDK_Windows#5]
i followed the 08PointCloudCaptureAndSave example.
now i want to write the same code for saving the IR and the RGB images but i can not find the commands similar to PointCloudWriter and other commands needed for saving.
also, when i check FrameReady.RGB i do not get 1, all the time i get 0. when checking FrameReady.depth or FrameReady.IR i get 1 .

if there is a sample code for IRCaptureAndSave and/or RGBCaptureAndSave or a list of commands it also can help
thank you

**Comment by peter-vzense** [comment]
you could reference the sample like below:
[05FrameCaptureAndSave](https://github.com/Vzense/Vzense_SDK_Windows/tree/master/Samples/DCAM560_Samples/05FrameCaptureAndSave)

**Comment by Rans1234** [comment]
i started with that sample but it only does depth save. i need the commands
for saving IR and RGB images

בתאריך יום ד׳, 20 ביולי 2022, 4:25, מאת Peter Liu ***@***.***

**Comment by peter-vzense** [comment]
you could reference the sample to write your code based on your requirement.

**Comment by Rans1234** [comment]
hello
i switched from C++ to python because the target platform for the
project is an NVIDIA JETSON NANO.
i found some answers in the python examples.
now i can get the Pointcloud and IR but i can not get from the camera
"frameready.rgb" , it is always returned as FALSE


‫בתאריך יום ו׳, 22 ביולי 2022 ב-6:47 מאת ‪Peter Liu‬‏
***@***.***‬‏>:‬

**Comment by Rans1234** [comment]
the following code:
while 1:
    ret, frameready = camera.Ps2_ReadNextFrame()
    if  ret !=0:
        print("Ps2_ReadNextFrame failed:",ret)
        time.sleep(1)
        continue
    if  frameready.mappedRGB:
        ret,frame = camera.Ps2_GetFrame(PsFrameType.PsMappedRGBFrame)
        if  ret == 0:
            curPath = os.getcwd()
            print (curPath)
            folder = curPath+ "/save"
            if not os.path.exists(folder):
                print("not exists")
                os.makedirs(folder)
            else:
                print("already exists")
            filename = folder + "/mappedrgb.bin"
            file = open(filename,"wb+")
            for i in range(frame.dataLen):
                file.write(c_uint8(frame.pFrameData[i]))

            file.close()
            print("save ok")
            break
        else:
            print("mappedrgb  error:",ret)

produce a file but that file can not be read

‫בתאריך יום ו׳, 22 ביולי 2022 ב-6:47 מאת ‪Peter Liu‬‏ <‪
***@***.***‬‏>:‬

**Comment by Rans1234** [comment]
there must be those code lines in the UTOOL app because that app can write RGB and IR images. it is only few lines but i can not guess how to do it. i need your help for that

**Comment by Rans1234** [comment]
those lines are copied from "06MappedRGBFrameCapture" . the exact lines i need are not given in any of the samples

**Comment by Rans1234** [comment]
the issue had been solved with one very simple line:
cv2.imwrite(filename,img)

should have been easier from the start....
thank you and you may close the issue
